name: CI
on:
  - push
  - pull_request

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  run:
    name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [14.18.0, 14, 16.0.0, 16, 18, 20, 22]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          # Node 14 is not available on macos anymore
          - os: macos-latest
            node: 14
          - os: macos-latest
            node: 14.18.0

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Run Coveralls
        # `master` should be a tag but they don't have one
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == 14
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
